version: '3.6'

services:

  mqtt:
    image: pascaldevink/rpi-mosquitto
    container_name: mosquitto
    ports:
      - "9001:9001"
      - "1883:1883"
    networks: 
      - back
    

  monitoring_api:
    image: rpi_api
    container_name: rpi_monitoring_api
    ports: 
      - "5001:5001"
    build:
      context: ./src/RpiSmartHouse.Monitoring.Api/
      dockerfile: Dockerfile
    depends_on:
      - mqtt
    networks: 
      - back

  fake_publisher:
    image: rpi_fake_publihser
    build:
      context: ./src/RpiSmartHouse.Publisher
      dockerfile: Dockerfile
    depends_on:
      - mqtt
    networks: 
      - back

networks:
    back: