version: '3'

services:
  # rpismarthouse.monitoring.api:
  #   image: rpi_sh_api
  #   ports: 
  #     - "5001:5001"
  #   build:
  #     context: .
  #     dockerfile: src/RpiSmartHouse.Monitoring.Api/Dockerfile

  rpismarthouse.publisher.fake:
    image: rpi_sh_publihser_fake
    build:
      context: .
      dockerfile: src/RpiSmartHouse.Publisher/Dockerfile

  mqtt:
    image: pascaldevink/rpi-mosquitto
    container_name: mosquitto
    ports:
      - "9001:9001"
      - "1883:1883"
